pages:
  stage: deploy
  script:
    - mkdir public
    - cp -r * public
    - Remove-Item -Recurse -Force public\.git -ErrorAction SilentlyContinue
    - Remove-Item -Force public\.gitlab-ci.yml -ErrorAction SilentlyContinue
  artifacts:
    paths:
      - public
  only:
    - main